In [6]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/aiexplorer77/internship-selection-prediction-dataset/Internship_Selection_Dataset.csv

In [7]:
df = pd.read_csv('/kaggle/input/datasets/aiexplorer77/internship-selection-prediction-dataset/Internship_Selection_Dataset.csv')

In [8]:
df.drop(columns=['extracurricular','college_tier','placement_training'],inplace=True)

In [9]:
df.drop(columns=['student_id'],inplace = True)

In [10]:
df

,CGPA,skills_score,projects_count,internships_done,communication_score,aptitude_score,coding_test_score,resume_score,hackathons_participated,certifications_count,linkedin_activity_score,github_score,soft_skills_score,interview_score,consistency_score,backlogs,selected
0,6.87,7,0,0,4,3,2,7,0,7,5,9,3,1,4,4,1
1,9.75,4,4,2,3,3,6,1,3,2,8,8,3,9,8,5,1
2,8.66,2,1,1,2,1,4,6,4,1,5,2,2,1,3,2,1
3,7.99,5,4,2,8,8,10,8,1,5,5,9,2,7,10,1,1
4,5.78,3,2,2,4,9,1,7,4,7,3,8,7,8,6,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9.29,8,3,1,10,2,4,6,4,5,10,2,6,5,3,4,0
9996,9.49,4,2,1,7,1,3,5,2,8,6,10,1,5,1,1,0
9997,9.73,8,0,0,1,4,4,9,3,6,4,5,9,10,2,3,1
9998,6.99,5,1,1,3,6,9,5,2,2,10,2,4,8,1,4,1
9999,6.09,3,3,0,5,6,4,6,4,9,1,1,5,7,8,3,1

In [11]:
df['selected'].value_counts()

selected
1    7374
0    2626
Name: count, dtype: int64

In [12]:
df.isnull().sum()

CGPA                       0
skills_score               0
projects_count             0
internships_done           0
communication_score        0
aptitude_score             0
coding_test_score          0
resume_score               0
hackathons_participated    0
certifications_count       0
linkedin_activity_score    0
github_score               0
soft_skills_score          0
interview_score            0
consistency_score          0
backlogs                   0
selected                   0
dtype: int64

In [13]:
df.sample(10)

,CGPA,skills_score,projects_count,internships_done,communication_score,aptitude_score,coding_test_score,resume_score,hackathons_participated,certifications_count,linkedin_activity_score,github_score,soft_skills_score,interview_score,consistency_score,backlogs,selected
6028,8.60,2,2,3,4,5,2,6,0,3,2,2,4,9,1,5,1
703,5.67,3,0,1,8,4,3,10,1,3,10,3,1,5,10,0,1
8404,7.27,7,2,3,9,5,4,4,1,4,4,5,7,2,6,4,1
9693,9.23,10,5,2,5,3,5,8,5,7,3,9,1,9,6,3,1
2736,9.96,8,0,1,10,3,4,2,0,4,9,8,1,9,10,4,1
2299,6.69,10,0,3,1,7,8,9,5,1,8,4,2,4,5,2,0
6109,9.72,3,0,3,5,6,6,6,4,9,3,5,10,6,2,4,1
3789,9.90,4,5,1,1,7,10,5,4,1,10,7,9,6,5,3,0
3394,9.50,6,4,1,7,8,3,2,1,6,2,3,10,4,2,3,0
846,5.43,9,5,1,8,9,4,3,5,8,8,9,4,2,9,5,1

In [14]:
X = df.iloc[:,0:16]
X

,CGPA,skills_score,projects_count,internships_done,communication_score,aptitude_score,coding_test_score,resume_score,hackathons_participated,certifications_count,linkedin_activity_score,github_score,soft_skills_score,interview_score,consistency_score,backlogs
0,6.87,7,0,0,4,3,2,7,0,7,5,9,3,1,4,4
1,9.75,4,4,2,3,3,6,1,3,2,8,8,3,9,8,5
2,8.66,2,1,1,2,1,4,6,4,1,5,2,2,1,3,2
3,7.99,5,4,2,8,8,10,8,1,5,5,9,2,7,10,1
4,5.78,3,2,2,4,9,1,7,4,7,3,8,7,8,6,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9.29,8,3,1,10,2,4,6,4,5,10,2,6,5,3,4
9996,9.49,4,2,1,7,1,3,5,2,8,6,10,1,5,1,1
9997,9.73,8,0,0,1,4,4,9,3,6,4,5,9,10,2,3
9998,6.99,5,1,1,3,6,9,5,2,2,10,2,4,8,1,4
9999,6.09,3,3,0,5,6,4,6,4,9,1,1,5,7,8,3

In [15]:
y = df.iloc[:,-1]
y

0       1
1       1
2       1
3       1
4       1
       ..
9995    0
9996    0
9997    1
9998    1
9999    1
Name: selected, Length: 10000, dtype: int64

In [16]:
# import machine learning models
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
# import cross validation function
from sklearn.model_selection import cross_val_score
# import numpy for mean and round
import numpy as np

# create Logistic Regression model
clf1 = LogisticRegression()
# create Random Forest model
clf2 = RandomForestClassifier()
# create KNN model
clf3 = KNeighborsClassifier()

# store model short name and model object in list
estimators = [
    ('lr', clf1),
    ('rf', clf2),
    ('knn', clf3)
]

# loop through each model one by one
for estimator in estimators:

    # estimator[1] gives actual model
    # perform 10-fold cross validation
    x = cross_val_score(
        estimator[1],   # model (clf1) is on the first index 
        X,              # input features
        y,              # target/output
        cv=10,          # 10 folds
        scoring='accuracy'
    )

    # estimator[0] gives model short name
    # np.mean(x) gives average accuracy
    # np.round(...,2) rounds to 2 decimal places
    print(estimator[0], np.round(np.mean(x), 2))
    
#Without loop:
#estimators[0][0]
#Inside loop:
#estimator[0]
#because loop already picks one tuple

lr 0.74
rf 0.74
knn 0.69

# Hard Voting

In [17]:
estimators = [
    ('lr', clf1),
    ('rf', clf2),
    ('knn', clf3)
]

In [13]:
from sklearn.ensemble import VotingClassifier
vc = VotingClassifier(estimators=estimators, voting='hard')
x = cross_val_score(vc, X, y, cv=10, scoring='accuracy' )
print(np.round(np.mean(x),2))

0.74

# Soft Voting

In [14]:
estimators = [
    ('lr', clf1),
    ('rf', clf2),
    ('knn', clf3)
]

In [15]:
from sklearn.ensemble import VotingClassifier
vc = VotingClassifier(estimators=estimators, voting='soft')
x = cross_val_score(vc, X, y, cv=10, scoring='accuracy')
print(np.round(np.mean(x),2))

0.73

# Weighted Voting

In [16]:
for i in range(1,4):
    for j in range(1,4):
        for k in range(1,4):
            vc = VotingClassifier(estimators=estimators, voting='soft', weights=[i, j,k])
            x = cross_val_score(vc, X,y, cv=10, scoring='accuracy' )
            print("for i={}, j={},k={}".format(i,j,k),np.round(np.mean(x),2))

for i=1, j=1,k=1 0.73
for i=1, j=1,k=2 0.73
for i=1, j=1,k=3 0.72
for i=1, j=2,k=1 0.74
for i=1, j=2,k=2 0.73
for i=1, j=2,k=3 0.73
for i=1, j=3,k=1 0.74
for i=1, j=3,k=2 0.73
for i=1, j=3,k=3 0.73
for i=2, j=1,k=1 0.74
for i=2, j=1,k=2 0.73
for i=2, j=1,k=3 0.73
for i=2, j=2,k=1 0.74
for i=2, j=2,k=2 0.74
for i=2, j=2,k=3 0.73
for i=2, j=3,k=1 0.74
for i=2, j=3,k=2 0.74
for i=2, j=3,k=3 0.73
for i=3, j=1,k=1 0.74
for i=3, j=1,k=2 0.74
for i=3, j=1,k=3 0.73
for i=3, j=2,k=1 0.74
for i=3, j=2,k=2 0.74
for i=3, j=2,k=3 0.73
for i=3, j=3,k=1 0.74
for i=3, j=3,k=2 0.74
for i=3, j=3,k=3 0.73

In [ ]:
from sklearn.svm import SVC

svm1 = SVC(probability=True, kernel='poly', degree=1)
svm2 = SVC(probability=True, kernel='poly', degree=2)
svm3 = SVC(probability=True, kernel='poly', degree=3)
svm4 = SVC(probability=True, kernel='poly', degree=4)
svm5 = SVC(probability=True, kernel='poly', degree=5)

estimators = [('svm1', svm1), ('svm2',svm2), ('svm3',svm3), ('svm4',svm4), ('svm5',svm5) ]

for estimator in estimators:
    x = cross_val_score(estimator[1], X,y, cv=10, scoring='accuracy' )
    print(estimator[0],np.round(np.mean(x),2))

svm1 0.74
svm2 0.74

In [20]:
from sklearn.ensemble import VotingClassifier
vc1 = VotingClassifier(estimators=estimators, voting='soft')
x = cross_val_score(vc1,X,y, cv=2, scoring='accuracy')
print(np.round(np.mean(x),2))

KeyboardInterrupt: